services:
  db-postgres:
    image: postgres
    ports: 
      - 5432:5432   
    restart: "always"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
  admin: 
    image: adminer
    ports: 
      - 8080:8080
    restart:  "always"
    depends_on:
      - "db-postgres"
  python: 
    container_name: python
    build: './py'
    ports: 
      - 8000:8000
    # restart:  "on-failure"
    depends_on:
      - "db-postgres"